spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://192.168.124.49:3360/read_write_splitting?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      jdbc-url: jdbc:mysql://192.168.124.50:3360/read_write_splitting?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

#MyBatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: huaxin.entity
